# Generated by Django 2.2.11 on 2020-11-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0010_auto_20201108_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='a_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_product_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_title',
            new_name='title',
        ),
    ]
